# -*- coding: utf-8 -*-
__title__ = "Rename Views"
__doc__ = """Version = 1.0
Date    = 30.11.2024
_____________________________________________________________________
Description:
Rename Views in Revit by using Find/Replace Logic.
_____________________________________________________________________
How-to:
-> Click on the button
-> Select Views
-> Define Renaming Rules
-> Rename Views
_____________________________________________________________________
Last update:
- [30.11.2024] - 1.0 RELEASE
_____________________________________________________________________
Author: JL Elarde"""

# â•¦â•”â•¦â•—â•”â•â•—â•”â•â•—â•¦â•â•—â•”â•¦â•—â•”â•â•—
# â•‘â•‘â•‘â•‘â• â•â•â•‘ â•‘â• â•¦â• â•‘ â•šâ•â•—
# â•©â•© â•©â•©  â•šâ•â•â•©â•šâ• â•© â•šâ•â• IMPORTS
#==================================================
# Regular + Autodesk
from Autodesk.Revit.DB import *

# pyRevit
from pyrevit import revit, forms



# â•¦  â•¦â•”â•â•—â•¦â•â•—â•¦â•”â•â•—â•”â•— â•¦  â•”â•â•—â•”â•â•—
# â•šâ•—â•”â•â• â•â•£â• â•¦â•â•‘â• â•â•£â• â•©â•—â•‘  â•‘â•£ â•šâ•â•—
#  â•šâ• â•© â•©â•©â•šâ•â•©â•© â•©â•šâ•â•â•©â•â•â•šâ•â•â•šâ•â• VARIABLES
#==================================================
from Autodesk.Revit.UI import UIDocument
doc   = __revit__.ActiveUIDocument.Document #type: Document
uidoc = __revit__.ActiveUIDocument          #type: UIDocument
app   = __revit__.Application               # Application


# â•”â•¦â•—â•”â•â•—â•¦â•”â•—â•”
# â•‘â•‘â•‘â• â•â•£â•‘â•‘â•‘â•‘
# â•© â•©â•© â•©â•©â•â•šâ• MAIN
#==================================================

#1ï¸âƒ£ Select Views

# Get Views - Selected in a ProjectBrowser
sel_el_ids = uidoc.Selection.GetElementIds()
sel_elem   = [doc.GetElement(e_id) for e_id in sel_el_ids]
sel_views  = [el for el in sel_elem if issubclass(type(el),View)]

# If none Selected - Promp SelectedViews from pyrevit.forms.select_views()
if not sel_views:
    sel_views = forms.select_views()

# Ensure Views Selected
if not sel_views:
    forms.alert('No Views Selected. Please Try Again', exitscript=True)

print("Done! ")

# #2ï¸âƒ£ðŸ…° Define Renaming Rule
# prefix  = 'AA-'
# find    = 'FloorPlan'
# replace = 'JL-Level'
# suffix  = '-XX'


#2ï¸âƒ£ðŸ…±ï¸ Define Renaming Rules (UI FORM)
# ðŸ‘‰https://revitpythonwrapper.readthedocs.io/en/latest/ui/forms.html#flexform
from rpw.ui.forms import (FlexForm, Label, TextBox, Separator, Button)
components = [Label('Prefix:'),  TextBox('prefix'),
              Label('Find:'),    TextBox('find'),
              Label('Replace:'), TextBox('replace'),
              Label('Suffix:'),  TextBox('suffix'),
              Separator(),       Button('Rename Views')]

form = FlexForm('Title', components)
form.show()

user_inputs = form.values #type: dict
prefix      = user_inputs['prefix']
find        = user_inputs['find']
replace     = user_inputs['replace']
suffix      = user_inputs['suffix']

#ðŸ”’ Start Transaction to make changes in project
t = Transaction(doc,'JL-Rename Views')

t.Start() #ðŸ”“

for view in sel_views:

    #3ï¸âƒ£ Create new View Name
    old_name = view.Name
    new_name = prefix + old_name.replace(find, replace) + suffix


    #4ï¸âƒ£ Rename Views (Ensure unique view name)
    for i in range(20):
        try:
            view.Name = new_name
            print('{} -> {}'.format(old_name, new_name))
            break
        except:
            new_name += "*"

t.Commit() #ðŸ”’

print('Done!')
